require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TheCoffeeShopMobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-dialogflow', :path => '../node_modules/react-native-dialogflow'

  pod 'react-native-voice', :path => '../node_modules/react-native-voice'

  target 'TheCoffeeShopMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'TheCoffeeShopMobile-tvOS' do
  # Pods for TheCoffeeShopMobile-tvOS

  target 'TheCoffeeShopMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
